# Docker Compose pour Agents Liminals (Next.js 15)
# Version: 3.0.0

version: '3.8'

services:
  app:
    build: .
    container_name: agents-liminals
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agents-liminals.rule=Host(`liminals.memoapp.eu`)"
      - "traefik.http.routers.agents-liminals.tls=true"
      - "traefik.http.routers.agents-liminals.tls.certresolver=letsencrypt"
      - "traefik.http.services.agents-liminals.loadbalancer.server.port=3000"
    networks:
      - agents-liminals-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  agents-liminals-network:
    driver: bridge

volumes:
  agents-liminals-data: